spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.239:8848
  application:
    name: smilemall-order
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.31.239
    virtual-host: /
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        concurrency:
        max-concurrency: 3
        prefetch: 10
        retry:
          enabled: true
          max-attempts: 3
        acknowledge-mode: manual
      type: simple
  redis:
    host: 192.168.31.239
    port: 6379
    password: smile
  session:
    timeout: 30m
    store-type: redis
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.239/smilemall_oms
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.smile.smilemall.entity
  global-config:
    db-config:
      id-type: auto

server:
  port: 5001