spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.1.15/smilemall_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: cn-smile-smilemall-product
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.15:8848
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.smile.smilemall.entity
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: 1
      logic-not-delete-value: 0

server:
  port: 6001