#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.1.22/smilemall_ums
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: cn-smile-smilemall-member
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.1.22:8848
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  type-aliases-package: cn.smile.smilemall.entity
#  global-config:
#    db-config:
#      id-type: auto
#
#
#server:
#  port: 4001