spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.239:3306/smilemall_wms
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.31.239
    password: smile
  session:
    store-type: redis
    timeout: 30m
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.239:8848
  application:
    name: cn-smile-smilemall-ware
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.smile.smilemall.entity
  global-config:
    db-config:
      id-type: auto

server:
  port: 7001